export const badWords = {
  ofensas: [
    "cuzão", "cuzao", "cuzona", "cuzaona", "cuzões", "cuzaos",
    "cuz4o", "cuza0", "filha da puta", "buceta", "odio preto",
    "puta", "puto", "putas", "putos", "bosta", "bostas",
    "caga sangue", "caga sangue", "caga-sangue",
    "caga-sangue", "cagão", "cagao", "cagona", "cagona",
    "cagões", "cagoes", "cagonas", "cagonas",
    "corno", "corna", "cornos", "cornas",
    "corno manso", "corna mansa", "cornos mansos", "cornas mansas",
    "boceta", "bocetas", "xoxota", "xoxotas",
    "buceta", "pau", "cu", "caralho", "merda", "porra", "foda", "fodase",
    "fuder", "fudendo", "fudida", "fudido", "viado", "viada", "bicha",
    "bixa", "bixona", "bixão", "bixonas", "bixao", "bixões", "viado", "viada",
    "viados", "viadas", "transa", "transando", "transada", "transado", "transas",
    "transar", "sexo", "sexy", "nude", "nudes", "pelada", "pelado", "peladas", "pelados",
    "xvideos", "pornhub", "xhamster", "redtube", "xnxx", "brazzers",
    "sexo oral", "sexo anal", "sexo vaginal", "sexo grupal",
    "sexo a três", "sexo a quatro", "sexo a cinco",
    "safada", "safado", "safadas", "safados",
    "tarada", "tarado", "taradas", "tarados",
    "putinha", "putinho", "putinhas", "putinhos",
    "prostituta", "prostituto", "prostitutas", "prostitutos",
    "prostituição", "prostituicao",
    "cachorra", "cachorro", "cachorras", "cachorros",
    "vagabunda", "vagabundo", "vagabundas", "vagabundos",
    "vagabundagem", "vagabundagens",
    "besta", "bestas",
    "idiota", "idiotas",
    "burra", "burro", "burras", "burros",
    "otária", "otário", "otárias", "otários",
    "otária do caralho", "otário do caralho",
    "boceta", "bocetas",
    "xoxota", "xoxotas",
    "perereca", "pererecas",
    "rola", "rolas",
    "pau no cu", "pau no cuzinho",
    "cu de pau", "cu de pauzinho",
    "cu de burro", "cu de burrozinho",
    "cu de vaca", "cu de vacazinha",
    "cu de boi", "cu de boizinho",  
    "cu de porco", "cu de porquinho",
    "cu de cavalo", "cu de cavalinho",
    "cu de cachorro", "cu de cachorrinho",
    "cu de gato", "cu de gatinho",
    "cu de rato", "cu de ratinho",
    "cu de leão", "cu de leãozinho",
    "cu de tigre", "cu de tigrezinho",
    "cu de onça", "cu de onçazinha",
    "cu de lobo", "cu de lobinho",
    "cu de urso", "cu de ursinho",
    "cu de elefante", "cu de elefantinho",
    "cu de girafa", "cu de girafinha",
    "cu de zebra", "cu de zebrazinha",
    "cu de macaco", "cu de macaquinho",
    "come merda", "comer merda",
    "chupa merda", "chupar merda",
    "bosta", "bostas",
    "chupar pau", "chupar rola",
    "chupar pica", "chupar pica",
    "pica", "picas",
    "pinto", "pintos",
    "caralho", "caralhos",
    "papai", "papais", "mamas",
    "teta", "tetas",
    "onlyfans", "peitos",
    "bundinha", "bundão", "bundas", "bundinhas", "bundões",
    "incesto", "incesto", "incestos",
    "zoofilia", "zoofilia", "zoofilias",
    "bestialidade", "bestialidades",
    "pedofilia", "pedofilia", "pedofilias",
    "estupro", "estuprar", "estuprador", "estupradora", "estupradores", "estupradoras",
    "abusar", "abuso", "abusador", "abusadora", "abusadores", "abusadoras",
    "molestar", "molestador", "molestadora", "molestadores", "molestadoras",
    "assediar", "assediador", "assediadora",
    "assediadores", "assediadoras",
    "pornografia", "pornografias",
    "obscenidade", "obscenidades",
    "safadeza", "safadezas",
    "taradice", "taradices",
    "putaria", "putarias",
    "prostituição", "prostituições",
    "vagabundagem", "vagabundagens",
    "meretriz", "meretrizes",
    "coroa", "coronas",
    "coroinha", "coroinhas",
    "ninfeta", "ninfetas",
    "ninfetinha", "ninfetinhas",
    "gostosa", "gostoso", "gostosas", "gostosão", "gostosona", "gostosonas", "gostosões",
    "sexy", "sexys",
    "sensual", "sensuais",
    "erótico", "erótica", "eróticos", "eróticas",
    "erotismo", "erotismos",
    "fetiche", "fetiches",
    "bondage", "bondages",
    "sadomasoquismo", "sadomasoquismos",
    "dominatrix", "dominatrixes",
    "submisso", "submissa", "submissos", "submissas",
    "dominador", "dominadora", "dominadores", "dominadoras",
    "masoquista", "masoquistas",
    "sadista", "sadistas",
    "orgia", "orgias",
    "swing", "swings",
    "swinger", "swingers",
    "sexo virtual", "sexo ao vivo",
    "sexo por webcam", "sexo por videochamada",
    "sexo por video chamada", "sexo por video-chamada",
    "sexo por video", "sexo por video",
    "sexo por vídeo", "sexo por vídeochamada", "sexo por vídeochamada",
    "sexo por vídeochamada", "sexo por vídeochamada",
    "punheta", "punhetas",
    "masturbação", "masturbacao", "masturbações", "masturbacoes",
    "broche", "broches", "boquete", "boquetes", "oral", "orais",
    "anal", "anais",
    "vaginal", "vaginais", "masturbar", "masturbar-se", "se masturbar",
    "foder", "foder-se", "se foder", "transar", "transar-se", "se transar",
    "dar o cu", "dar o cuzinho", "dar o cuzinho",
    "dar a bunda", "dar a bundinha", "dar a bundinha",
    "dar a raba", "dar a rabinha", "dar a rabinha",
    "dar a bunda", "dar a bundinha", "dar a bundinha",
    "dar a raba", "dar a rabinha", "dar a rabinha",
    "pegação", "pegacao", "pegacões", "pegacoes",
    "ficar pelado", "ficar pelada", "ficar pelados", "ficar peladas",
    "ficar nu", "ficar nua", "ficar nus", "ficar nuas",
    "tirar a roupa", "tirar as roupas",
    "mostrar o corpo", "mostrar o corpo nu", "mostrar o corpo nua",
    "mostrar o corpo nus", "mostrar o corpo nuas",
    "mostrar os peitos", "mostrar as tetas", "mostrar as mamas",
    "mostrar a bunda", "mostrar a raba", "mostrar o cu",
    "mostrar o cuzinho", "mostrar o cuzinho",
    "exibir o corpo", "exibir o corpo nu", "exibir o corpo nua",
    "exibir o corpo nus", "exibir o corpo nuas",
    "exibir os peitos", "exibir as tetas", "exibir as mamas",
    "exibir a bunda", "exibir a raba", "exibir o cu",
    "exibir o cuzinho", "exibir o cuzinho",
    "sexo casual", "sexo casual", "sexo casuais",
    "sexo seguro", "sexo seguro", "sexos seguros",
    "sexo sem camisinha", "sexo sem camisinha", "sexos sem camisinha",
    "sexo sem proteção", "sexo sem proteção", "sexos sem proteção",
    "sexo sem protecao", "sexo sem protecao", "sexos sem protecao",
    "sexo sem preservativo", "sexo sem preservativo", "sexos sem preservativo",
    "sexo sem camisinha", "sexo sem camisinha", "sexos sem camisinha",
    "sexo selvagem", "sexo selvagem", "sexos selvagens",
    "sexo oral", "sexo oral", "sexos orais",
    "sexo anal", "sexo anal", "sexos anais",
    "sexo vaginal", "sexo vaginal", "sexos vaginais",
    "sexo grupal", "sexo grupal", "sexos grupais",
    "sexo a três", "sexo a três", "sexos a três",
    "sexo a quatro", "sexo a quatro", "sexos a quatro",
    "sexo a cinco", "sexo a cinco", "sexos a cinco",
    "sexo a seis", "sexo a seis", "sexos a seis",
    "sexo a sete", "sexo a sete", "sexos a sete",
    "sexo a oito", "sexo a oito", "sexos a oito",
    "sexo a nove", "sexo a nove", "sexos a nove",
    "sexo a dez", "sexo a dez", "sexos a dez",
    "sexo em grupo", "sexo em grupo", "sexos em grupo",
    "sexo em público", "sexo em público", "sexos em público",
    "sexo em publico", "sexo em publico", "sexos em publico",
    "sexo selvagem", "sexo selvagem", "sexos selvagens",
    "sexo ao ar livre", "sexo ao ar livre", "sexos ao ar livre",
    "sexo ao vivo", "sexo ao vivo", "sexos ao vivo",
    "sexo por webcam", "footjob", "footjobs",
    "handjob", "handjobs",
    "striptease", "stripteases",
    "lap dance", "lap dances",
    "sexo tântrico", "sexo tantrico", "sexos tântricos", "sexos tantricos",
    "sexo telefônico", "sexo telefonico", "sexos telefônicos", "sexos telefonicos",
    "sexo virtual", "sexo virtual", "sexos virtuais",
    "blowjob", "blowjobs",
    "deepthroat", "deepthroats",
  ],

  frases: [
    "odeio judeus", "judeu é tudo isso", "judeu é tudo aquilo", 
    "judeu é ladrão", "judeu é avarento",
    "judeu é ganancioso", "judeu é mesquinho",
    "judeu é sujo", "judeu é porco",
    "judeu é nojento", "judeu é imundo",
    "judeu é maldito", "judeu é amaldiçoado",
    "judeu é desgraçado", "judeu é praga",
    "judeu é câncer", "judeu é peste",
    "judeu é escória", "judeu é lixo",
    "judeu é verme", "judeu é parasita",
    "judeu é diabo", "judeu é demônio",
    "judeu é satã", "judeu é satanás",
    "judeu é anticristo", "judeu é herege",
    "gays são doentes", "gays são anormais",

  ]
};

// Junta todas as palavras/frases em um único array para o filtro
const allBadWords = Object.values(badWords).flat();

export function isTextInappropriate(text) {
  if (!text) return false;
  const lower = text.toLowerCase();
  return allBadWords.some(word => lower && lower.includes(word));
}